#!/usr/bin/env python3
"""
Converte LAS para PLY binario para abrir em CloudCompare quando o build local
nao tem suporte ao formato LAS/LAZ.
"""

import argparse
import sys
from pathlib import Path

try:
    import laspy
    import numpy as np
except ImportError as e:
    print(f"ERRO: biblioteca faltando: {e}")
    print("Instalar com: pip install laspy numpy")
    sys.exit(1)


def scale_to_u8(values):
    values = np.asarray(values)
    if values.size == 0:
        return values.astype(np.uint8)
    vmin = float(values.min())
    vmax = float(values.max())
    if vmax <= vmin:
        return np.full(values.shape, 180, dtype=np.uint8)
    scaled = 40 + 215 * (values.astype(np.float64) - vmin) / (vmax - vmin)
    return np.clip(scaled, 0, 255).astype(np.uint8)


def write_ply_from_las(las_path, ply_path, max_points=None):
    las_path = Path(las_path)
    ply_path = Path(ply_path)

    las = laspy.read(str(las_path))
    total = len(las.points)
    if total == 0:
        raise ValueError("LAS sem pontos")

    if max_points and total > max_points:
        idx = np.linspace(0, total - 1, max_points, dtype=np.int64)
        xs = las.x[idx]
        ys = las.y[idx]
        zs = las.z[idx]
        intensities = las.intensity[idx]
    else:
        xs = las.x
        ys = las.y
        zs = las.z
        intensities = las.intensity

    n_points = len(xs)
    colors = scale_to_u8(intensities)

    vertex_dtype = np.dtype([
        ("x", "<f8"),
        ("y", "<f8"),
        ("z", "<f8"),
        ("red", "u1"),
        ("green", "u1"),
        ("blue", "u1"),
    ])
    vertices = np.empty(n_points, dtype=vertex_dtype)
    vertices["x"] = xs
    vertices["y"] = ys
    vertices["z"] = zs
    vertices["red"] = colors
    vertices["green"] = colors
    vertices["blue"] = colors

    header = (
        "ply\n"
        "format binary_little_endian 1.0\n"
        "comment generated by las_to_ply_ajr.py\n"
        f"element vertex {n_points}\n"
        "property double x\n"
        "property double y\n"
        "property double z\n"
        "property uchar red\n"
        "property uchar green\n"
        "property uchar blue\n"
        "end_header\n"
    ).encode("ascii")

    with open(ply_path, "wb") as f:
        f.write(header)
        vertices.tofile(f)

    print(f"PLY gerado: {ply_path}")
    print(f"Pontos: {n_points:,} de {total:,}")
    print(f"Tamanho: {ply_path.stat().st_size / 1e6:.1f} MB")


def main():
    parser = argparse.ArgumentParser(description="Converter LAS para PLY binario")
    parser.add_argument("las")
    parser.add_argument("-o", "--output", required=True)
    parser.add_argument(
        "--max-points",
        type=int,
        default=None,
        help="Opcional: subamostrar para no maximo N pontos",
    )
    args = parser.parse_args()
    write_ply_from_las(args.las, args.output, args.max_points)


if __name__ == "__main__":
    main()
